### ISSUE TITLE
what do you think is needed to implement ordered collections?

### ISSUE THREAD

**Issue by faceyspacey** [spencercarli/node-ddp-client#1]

**Comment by faceyspacey** [comment]
is the prescribed way to work with ordered collections something like this: **use `subscribe` rather than `observe` and order the docs on the server within your publish function, and then manually re-order the set on the react native client? Do they come pre-ordered? If so, then I guess you only need to re-order them, if you have various client-only sorting needs for the same data set** 

...and then `observe` just works by letting you assign callbacks to the _entire_ collection brought in by subscriptions, i.e. rather than allowing you to further filter the set with `limit` and `sort`, correct? 

---

I really wonder what it would take to bring in minimongo to React Native. It can't be that challenging. Have you done any research into this area? What did you find?

**Comment by spencercarli** [comment]
Hey @faceyspacey! In all honesty I'm not sure what it would take to get ordered collections up and running. As far as I understand ordered collections, though outlined in the DDP spec, have not been [implemented on the Meteor side](https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md).

I mostly forked this in order to fix a reconnect bug that was happening with the original. I've been doing some research into the [`react-native-meteor`](https://github.com/inProgress-team/react-native-meteor) package to handle the ddp side of things. The author of that package has implemented [`minimongo-cache`](https://github.com/petehunt/minimongo-cache) which provides a pretty similar API to what you're used to with Meteor.

I'm still doing my research but for future projects I can likely see going the route of `react-native-meteor`.

**Comment by spencercarli** [comment]
Closing this as this fork is more of a stopgap solution.
